# generated by datamodel-codegen:
#   filename:  audience_profile.schema.json
#   timestamp: 2026-05-16T17:29:29+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class ToleranceBands(BaseModel):
    min: Annotated[float, Field(ge=0.0, le=1.0)]
    max: Annotated[float, Field(ge=0.0, le=1.0)]


class TriggerSets(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    dnf_triggers: Annotated[
        list[str],
        Field(
            description="Conditions that cause this audience to DNF (e.g. hero_dies, no_resolution)."
        ),
    ]
    satisfaction_triggers: Annotated[
        list[str],
        Field(
            description="Elements that guarantee re-read / recommendation (e.g. earned_hea, banter)."
        ),
    ]


class ReaderPersona(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    persona_id: str
    name: str
    description: str
    weight: Annotated[
        float | None,
        Field(
            description="Relative weight in aggregate reader satisfaction score.",
            ge=0.0,
            le=1.0,
        ),
    ] = None
    reading_preferences: Annotated[
        dict[str, str | float | bool] | None,
        Field(description="Key-value pairs of this persona's specific preferences."),
    ] = None


class AudienceProfile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    profile_id: str
    version: str
    reader_lens: Annotated[
        str,
        Field(
            description="Plain-language description of the primary reader's perspective and expectations."
        ),
    ]
    tolerance_bands: Annotated[
        dict[str, ToleranceBands],
        Field(
            description="Per-dimension tolerance range (0–1) the audience will accept without DNF.",
            examples=[
                {
                    "complexity": {"min": 0.2, "max": 0.7},
                    "darkness": {"min": 0.0, "max": 0.6},
                }
            ],
        ),
    ]
    expectation_set: Annotated[
        list[str],
        Field(
            description="Explicit expectations this audience brings (e.g. hea_required, no_cliffhanger_endings)."
        ),
    ]
    trigger_sets: TriggerSets
    reader_personas: Annotated[list[ReaderPersona] | None, Field(min_length=1)] = None
