# generated by datamodel-codegen:
#   filename:  author_profile.schema.json
#   timestamp: 2026-05-16T17:29:29+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class MoodDistribution(BaseModel):
    declarative: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    interrogative: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    imperative: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    exclamatory: Annotated[float | None, Field(ge=0.0, le=1.0)] = None


class SentenceLevel(BaseModel):
    length_mean_words: Annotated[float | None, Field(ge=1.0)] = None
    length_std_words: Annotated[float | None, Field(ge=0.0)] = None
    opener_entropy_min: Annotated[float | None, Field(ge=0.0)] = None
    mood_distribution: MoodDistribution | None = None


class DiversityMetric(StrEnum):
    TTR = "TTR"
    MTLD = "MTLD"
    VOCD_D = "vocd_D"


class FormalityRegister(StrEnum):
    VERY_CASUAL = "very_casual"
    CASUAL = "casual"
    NEUTRAL = "neutral"
    FORMAL = "formal"
    VERY_FORMAL = "very_formal"


class Lexical(BaseModel):
    diversity_metric: DiversityMetric | None = None
    diversity_target: float | None = None
    formality_register: FormalityRegister | None = None
    rare_word_frequency: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    concrete_noun_ratio: Annotated[float | None, Field(ge=0.0, le=1.0)] = None


class Syntactic(BaseModel):
    subordinate_clause_rate: Annotated[float | None, Field(ge=0.0)] = None
    parallel_structure_rate: Annotated[float | None, Field(ge=0.0)] = None
    passive_voice_rate_max: Annotated[float | None, Field(ge=0.0, le=1.0)] = None


class TagStyle(StrEnum):
    MINIMAL = "minimal"
    MODERATE = "moderate"
    DESCRIPTIVE = "descriptive"


class Dialogue(BaseModel):
    to_narration_ratio: Annotated[float | None, Field(ge=0.0)] = None
    internal_monologue_share: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    tag_style: TagStyle | None = None


class Sensory(BaseModel):
    visual: Annotated[float | None, Field(ge=0.0)] = None
    auditory: Annotated[float | None, Field(ge=0.0)] = None
    olfactory: Annotated[float | None, Field(ge=0.0)] = None
    gustatory: Annotated[float | None, Field(ge=0.0)] = None
    tactile: Annotated[float | None, Field(ge=0.0)] = None
    proprioceptive: Annotated[float | None, Field(ge=0.0)] = None


class Pacing(BaseModel):
    paragraph_length_mean_words: Annotated[float | None, Field(ge=1.0)] = None
    short_long_alternation_index: Annotated[float | None, Field(ge=0.0, le=1.0)] = None


class Metaphor(BaseModel):
    figurative_per_1k: Annotated[float | None, Field(ge=0.0)] = None
    domain_bias: list[str] | None = None


class Subtext(BaseModel):
    modal_hedge_per_1k: Annotated[float | None, Field(ge=0.0)] = None
    adverb_density: Annotated[float | None, Field(ge=0.0)] = None
    adjective_stacking_max: Annotated[int | None, Field(ge=1)] = None


class Cadence(BaseModel):
    em_dash_per_1k_max: Annotated[float | None, Field(ge=0.0)] = None
    semicolon_per_1k: Annotated[float | None, Field(ge=0.0)] = None
    ellipsis_per_1k: Annotated[float | None, Field(ge=0.0)] = None


class VoiceAxes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sentence_level: Annotated[
        SentenceLevel | None,
        Field(description="Sentence length mean/std, opener entropy, mood distribution."),
    ] = None
    lexical: Annotated[
        Lexical | None,
        Field(description="Vocabulary diversity, register, rare word frequency."),
    ] = None
    syntactic: Annotated[
        Syntactic | None,
        Field(description="Clause complexity, subordination, parallelism."),
    ] = None
    dialogue: Annotated[
        Dialogue | None,
        Field(description="Dialogue-to-narration ratio and internal monologue share."),
    ] = None
    sensory: Annotated[
        Sensory | None,
        Field(description="Sensory token density by modality (tokens per 1000 words)."),
    ] = None
    pacing: Annotated[
        Pacing | None,
        Field(description="Paragraph length and scene-transition cadence."),
    ] = None
    metaphor: Annotated[
        Metaphor | None,
        Field(description="Figurative language density and domain bias."),
    ] = None
    subtext: Annotated[Subtext | None, Field(description="Modal hedge and adverb density.")] = None
    cadence: Annotated[
        Cadence | None,
        Field(description="Punctuation signature — em dash, semicolon, ellipsis rates."),
    ] = None


class CalibrationHistoryItem(BaseModel):
    calibration_run_id: str
    timestamp: AwareDatetime
    notes: str | None = None


class AuthorProfile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    profile_id: str
    version: str
    display_name: Annotated[str, Field(description="Pen name.")]
    voice_axes: Annotated[
        VoiceAxes,
        Field(
            description="Target values per voice axis group. All axes are universal and measurable; values vary per author."
        ),
    ]
    forbidden_constructions: Annotated[
        list[str] | None,
        Field(description="Regex patterns for constructions this author never uses."),
    ] = None
    enforcement_weights: Annotated[
        dict[str, float],
        Field(
            description="Weight (0–1) assigned to each voice axis group when computing aggregate fidelity distance."
        ),
    ]
    calibration_history: Annotated[
        list[CalibrationHistoryItem] | None,
        Field(description="References to calibration runs that updated this profile."),
    ] = None
