# generated by datamodel-codegen:
#   filename:  genre_profile.schema.json
#   timestamp: 2026-05-16T17:29:29+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class GenreModuleStatus(StrEnum):
    VALIDATED = "validated"
    SCAFFOLD = "scaffold"
    EXPERIMENTAL = "experimental"


class TargetChapterRange(BaseModel):
    min: Annotated[int, Field(ge=1)]
    max: Annotated[int, Field(ge=1)]


class RequiredSceneSlot(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    slot_id: str
    description: str
    target_chapter_range: TargetChapterRange | None = None
    required: bool


class Operator(StrEnum):
    GTE = "gte"
    LTE = "lte"
    GT = "gt"
    LT = "lt"
    EQ = "eq"


class QualityGate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    gate_id: str
    metric: str
    threshold: float
    operator: Operator
    description: str | None = None


class SelfAuditRubricItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    item_id: str
    question: str
    weight: Annotated[float, Field(ge=0.0, le=1.0)]


class HeatScale(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    min: Annotated[int, Field(ge=1)]
    max: Annotated[int, Field(ge=1)]
    anchor_definitions: Annotated[
        dict[str, str] | None, Field(description="Map of integer level → label.")
    ] = None


class WordCountRange(BaseModel):
    min: Annotated[int, Field(ge=1)]
    max: Annotated[int, Field(ge=1)]


class ChapterCountRange(BaseModel):
    min: Annotated[int, Field(ge=1)]
    max: Annotated[int, Field(ge=1)]


class PovDefault(StrEnum):
    FIRST_PERSON = "first_person"
    CLOSE_THIRD = "close_third"
    OMNISCIENT = "omniscient"
    MULTIPLE_POV = "multiple_pov"


class TenseDefault(StrEnum):
    PAST = "past"
    PRESENT = "present"


class StructuralConventions(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    word_count_range: WordCountRange
    chapter_count_range: ChapterCountRange
    act_structure: Annotated[
        str | None,
        Field(description="e.g. three_act, four_act, hero_journey, save_the_cat."),
    ] = None
    pov_default: PovDefault | None = None
    tense_default: TenseDefault | None = None


class Category(StrEnum):
    MUST_HAVE = "must_have"
    COMMONLY_LOVED = "commonly_loved"
    TABOO = "taboo"
    FRESH_TWIST = "fresh_twist"


class TropeLibraryItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trope_id: str
    name: str
    category: Category | None = None
    required_beats: list[str] | None = None


class GenreProfile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    profile_id: str
    version: str
    genre_name: str
    genre_module_status: Annotated[
        GenreModuleStatus,
        Field(
            description="validated = production-ready; scaffold = structure exists, not tuned; experimental = prototype."
        ),
    ]
    scene_function_vocabulary: Annotated[
        list[str],
        Field(
            description="Allowed scene function labels for this genre (e.g. setup_tension, meet_cute, black_moment)."
        ),
    ]
    required_scene_slots: list[RequiredSceneSlot] | None = None
    quality_gates: list[QualityGate] | None = None
    self_audit_rubric: Annotated[
        list[SelfAuditRubricItem] | None,
        Field(description="Rubric items for the self-audit critic after each scene."),
    ] = None
    heat_scale: Annotated[
        HeatScale | None, Field(description="Genre-defined intimacy intensity scale.")
    ] = None
    structural_conventions: StructuralConventions
    trope_library: list[TropeLibraryItem] | None = None
    reader_contract: Annotated[
        list[str] | None,
        Field(
            description="Promise types that must be opened and resolved (e.g. romantic_tension, hea_or_hfn)."
        ),
    ] = None
