# generated by datamodel-codegen:
#   filename:  goal_profile.schema.json
#   timestamp: 2026-05-16T17:29:29+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Intent(StrEnum):
    KDP_HIGH_REVENUE = "kdp_high_revenue"
    LITERARY_AWARD_TARGET = "literary_award_target"
    PERSONAL_VANITY = "personal_vanity"
    SERIES_BRAND = "series_brand"


class PrecedenceOrderEnum(StrEnum):
    SENSITIVITY = "sensitivity"
    GOAL = "goal"
    GENRE = "genre"
    AUDIENCE = "audience"
    AUTHOR = "author"
    UNIVERSAL = "universal"


class ConflictPrecedenceRule(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    axis: Annotated[str, Field(description="e.g. max_heat_level, word_count, pov_distance.")]
    precedence_order: Annotated[
        list[PrecedenceOrderEnum],
        Field(description="First profile in list wins the conflict for this axis."),
    ]


class WeightOverrides(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    critic_weights: dict[str, float] | None = None
    reader_weights: dict[str, float] | None = None


class Operator(StrEnum):
    GTE = "gte"
    LTE = "lte"
    GT = "gt"
    LT = "lt"
    EQ = "eq"


class SuccessCriterion(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    criterion_id: str
    metric: str
    threshold: float
    operator: Operator
    description: str | None = None


class GoalProfile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    profile_id: str
    version: str
    intent: Annotated[
        Intent,
        Field(description="Primary publishing intent driving all convergence decisions."),
    ]
    conflict_precedence_rules: Annotated[
        list[ConflictPrecedenceRule],
        Field(
            description="Per-axis precedence overrides. Sensitivity always wins on sensitivity axes regardless of these rules."
        ),
    ]
    weight_overrides: Annotated[
        WeightOverrides | None,
        Field(description="Convergence weight overrides for critics and readers."),
    ] = None
    success_criteria: list[SuccessCriterion]
