# generated by datamodel-codegen:
#   filename:  romance_module.schema.json
#   timestamp: 2026-05-16T17:29:29+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class HeatLevel(StrEnum):
    SWEET = "sweet"
    SENSUAL = "sensual"
    STEAMY = "steamy"
    EROTIC = "erotic"


class TonalMode(StrEnum):
    WARM_COMMERCIAL = "warm_commercial"
    FUNNY_AND_LIGHT = "funny_and_light"
    ANGSTY_EMOTIONAL = "angsty_emotional"
    DARK_AND_INTENSE = "dark_and_intense"
    GROUNDED_LITERARY = "grounded_literary"


class SexSceneSpec(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    first_sex_scene_by_chapter: Annotated[
        int | None,
        Field(
            description="Chapter by which the first sex scene must appear. Null = no constraint. For erotica: typically chapter 2.",
            ge=1,
        ),
    ] = None
    frequency_min_per_n_chapters: Annotated[
        int | None,
        Field(
            description="Minimum sex scene frequency (1 per N chapters). For erotica: typically 1 per 3 chapters.",
            ge=1,
        ),
    ] = None
    escalation_enforced: Annotated[
        bool | None,
        Field(
            description="If true, no two adjacent explicit scenes may repeat the same beat type (IntimacyEscalationLedger enforces)."
        ),
    ] = True
    interiority_budget_pct_max: Annotated[
        float | None,
        Field(
            description="Max interiority fraction in explicit scenes. For erotica: 0.20.",
            ge=0.0,
            le=1.0,
        ),
    ] = None


class Shape(StrEnum):
    SLOW_BURN = "slow_burn"
    MEDIUM_BURN = "medium_burn"
    FAST_BURN = "fast_burn"
    STEEP_EROTICA = "steep_erotica"


class HeatCurve(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    shape: Annotated[
        Shape | None,
        Field(
            description="Overall heat escalation shape. 'steep_erotica' requires first explicit scene by chapter 2."
        ),
    ] = None
    peak_act: Annotated[
        int | None, Field(description="Act in which heat curve peaks.", ge=1, le=3)
    ] = None


class RomanceModule(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    genre_id: Annotated[
        str, Field(description="Must be 'romance_module_v1' or a subtype identifier.")
    ]
    HEA_required: Annotated[
        bool,
        Field(
            description="Happily Ever After ending required. True for standard romance. Set false only if HFN_allowed=true (series book that defers HEA)."
        ),
    ]
    HFN_allowed: Annotated[
        bool,
        Field(
            description="Happily For Now acceptable as book-level resolution (series position > 1). If both HEA_required and HFN_allowed are false this is an invalid config."
        ),
    ]
    heat_level: Annotated[
        HeatLevel,
        Field(
            description="Heat ceiling for this romance module instance. Must not exceed sensitivity_profile.heat_ceiling."
        ),
    ]
    tonal_mode: Annotated[
        TonalMode | None,
        Field(
            description="Tone for this romance (e.g. warm_commercial, funny_and_light, angsty_emotional, dark_and_intense). Controls pacing target selection from voice_profile."
        ),
    ] = None
    consent_arc_required: Annotated[
        bool,
        Field(
            description="Enthusiastic consent arc required for all explicit scenes. Sacred — cannot be set false by Goal profile."
        ),
    ]
    sex_scene_spec: Annotated[
        SexSceneSpec | None,
        Field(description="Sex scene requirements. Required when heat_level >= sensual."),
    ] = None
    heat_curve: Annotated[
        HeatCurve | None,
        Field(
            description="Heat escalation curve specification. Stub — formalize curve shape taxonomy during Phase 5 T5.2 implementation."
        ),
    ] = None
    tropes_activated: Annotated[
        list[str],
        Field(
            description="List of romance tropes active for this book. Each activated trope creates required beats in TropeCommitmentLedger."
        ),
    ]
    no_fly_additions: Annotated[
        list[str] | None,
        Field(
            description="Romance-module-specific additions to the voice_profile no_fly_words list (e.g. genre clichés)."
        ),
    ] = None
    meet_cute_required: Annotated[
        bool | None,
        Field(description="Whether a meet-cute scene is required (standard romance: true)."),
    ] = True
    grand_gesture_required: Annotated[
        bool | None,
        Field(
            description="Whether a grand gesture (public or private) is required before HEA/HFN."
        ),
    ] = True
    power_dynamic_arc: Annotated[
        str | None,
        Field(
            description="Optional power dynamic type (e.g. boss_employee, age_gap, class_difference). When set, creates a required arc beat to resolve or contextualize the dynamic before HEA. Stub — expand during Phase 5 T5.2."
        ),
    ] = None
