# generated by datamodel-codegen:
#   filename:  sensitivity_profile.schema.json
#   timestamp: 2026-05-16T17:29:29+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class ContentDomainPolicies(StrEnum):
    ALLOW = "allow"
    ALLOW_WITH_CONSTRAINTS = "allow_with_constraints"
    PROHIBIT = "prohibit"


class RestrictionLevel(StrEnum):
    PROHIBITED = "prohibited"
    FLAGGED = "flagged"


class VocabularyRestriction(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    term_or_regex: str
    restriction_level: Annotated[
        RestrictionLevel,
        Field(description="prohibited = never output; flagged = critic review required."),
    ]
    notes: str | None = None


class RepresentationPolicy(BaseModel):
    authenticity_requirements: list[str] | None = None
    language_restrictions: list[str] | None = None


class SensitivityProfile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    profile_id: str
    version: str
    sacred: Annotated[
        Literal[True],
        Field(
            description="Always true. Marks that Goal cannot loosen this profile's hard_thresholds."
        ),
    ]
    content_domain_policies: Annotated[
        dict[str, ContentDomainPolicies],
        Field(
            description="Map of content domain → policy.",
            examples=[
                {
                    "sexual_content": "allow",
                    "graphic_violence": "allow_with_constraints",
                    "child_harm": "prohibit",
                    "self_harm": "prohibit",
                }
            ],
        ),
    ]
    vocabulary_restrictions: list[VocabularyRestriction] | None = None
    audience_markers: Annotated[
        list[str],
        Field(
            description="Applicable audience labels (e.g. adult_unrestricted, ya_safe, new_adult)."
        ),
    ]
    hard_thresholds: Annotated[
        dict[str, float],
        Field(
            description="Sacred numeric thresholds that cannot be loosened by Goal profile. x-sacred: true.",
            examples=[{"max_heat_level": 5, "max_violence_intensity": 4}],
        ),
    ]
    auto_content_warnings: Annotated[
        list[str] | None,
        Field(description="Content warning strings auto-injected into the publication package."),
    ] = None
    representation_policy: Annotated[
        RepresentationPolicy | None,
        Field(description="Policies for marginalized group depiction."),
    ] = None
