# generated by datamodel-codegen:
#   filename:  voice_profile.schema.json
#   timestamp: 2026-05-16T17:29:29+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class StyleMarkers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sentence_length_histogram: Annotated[
        dict[str, float] | None,
        Field(
            description="Target % of sentences per word-count bucket (1-5, 6-10, 11-20, 21-35, 36-50, 51+). Stub — expand during Phase 4."
        ),
    ] = None
    em_dash_rate_per_1000: Annotated[
        float | None, Field(description="Target em-dash rate.", ge=0.0)
    ] = None
    em_dash_ceiling: Annotated[float | None, Field(ge=0.0)] = None
    dialogue_ratio_target: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    interiority_pct_target: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    sensory_density_per_1k: Annotated[float | None, Field(ge=0.0)] = None
    modality_ratios: Annotated[
        dict[str, float] | None,
        Field(
            description="Target fraction of sensory references per modality (sight, sound, touch, smell, taste, proprioception)."
        ),
    ] = None
    lexical_diversity_target: Annotated[
        float | None, Field(description="TTR/MTLD target.", ge=0.0, le=1.0)
    ] = None
    hedge_word_ceilings: Annotated[
        dict[str, float] | None,
        Field(description="Per-hedge-word ceiling per 1000 words."),
    ] = None
    filter_word_ceilings: Annotated[
        dict[str, float] | None,
        Field(description="Per-filter-word ceiling per 1000 words."),
    ] = None


class Severity(StrEnum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class NoFlyPattern(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pattern: Annotated[str, Field(description="Regex pattern.")]
    severity: Annotated[Severity, Field(description="high=REJECT, medium=flag, low=warn.")]
    category: Annotated[
        str,
        Field(
            description="Pattern category (e.g. visceral_cliche, gaze_cliche, hedge_construction)."
        ),
    ]


class HeatLevel(StrEnum):
    SWEET = "sweet"
    SENSUAL = "sensual"
    STEAMY = "steamy"
    EROTIC = "erotic"


class Register(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    heat_level: HeatLevel | None = None
    tonal_mode: Annotated[
        str | None,
        Field(
            description="e.g. warm_commercial, literary_precise, funny_and_light. Stub — enumerate during Phase 4."
        ),
    ] = None


class PacingTargets(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    avg_sentence_length: float | None = None
    avg_paragraph_length_words: float | None = None
    dialogue_pct: float | None = None
    sensory_density_per_1000: float | None = None
    interiority_pct: float | None = None


class CalibrationHistoryItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    round: Annotated[int, Field(ge=1)]
    date: date_aliased
    trigger: str
    delta_summary: str | None = None


class VoiceProfile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    profile_id: Annotated[str, Field(description="Unique profile identifier.")]
    profile_name: Annotated[
        str, Field(description="Human-readable name (e.g. 'default', 'alex-river-v1').")
    ]
    profile_version: Annotated[
        str,
        Field(description="Semantic version (e.g. '1.0.0'). Bumped on meaningful change."),
    ]
    series_id: Annotated[
        str | None,
        Field(description="Series this profile is scoped to. Null for universal profiles."),
    ] = None
    style_markers: Annotated[
        StyleMarkers,
        Field(
            description="Measurable voice axes. Maps to Bunko schema §3–11. Stub — enumerate all sub-fields during Phase 4 T4.1 implementation."
        ),
    ]
    no_fly_words: Annotated[
        list[str],
        Field(
            description="Hard-banned words or multi-word phrases. Any occurrence = REJECT. See Bunko schema §4."
        ),
    ]
    no_fly_patterns: Annotated[
        list[NoFlyPattern],
        Field(description="Regex-based forbidden constructions. See Bunko schema §12."),
    ]
    register_: Annotated[
        Register | None, Field(alias="register", description="Tonal register settings.")
    ] = None
    pacing_targets: Annotated[
        dict[str, PacingTargets],
        Field(
            description="Per-scene-type pacing targets. Mirrors Bunko schema §8. Keys are scene_type values."
        ),
    ]
    exemplar_pool: Annotated[
        list[dict[str, Any]] | None,
        Field(
            description="Reference to computed voice-axis measurements derived from corpus (no prose retained). Stub — expand during Phase 6 Voice Extraction Pipeline."
        ),
    ] = None
    enforcement: Annotated[
        dict[str, Any] | None,
        Field(
            description="Conformance thresholds and dimension weights. Mirrors Bunko schema §13. Stub — expand during Phase 4."
        ),
    ] = None
    calibration_history: Annotated[
        list[CalibrationHistoryItem] | None,
        Field(
            description="Ordered log of recalibration rounds. Append-only. Mirrors Bunko schema §14."
        ),
    ] = None
