# generated by datamodel-codegen:
#   filename:  ai_tell_catalog.schema.json
#   timestamp: 2026-05-16T15:42:47+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Severity(RootModel[int]):
    root: Annotated[
        int,
        Field(
            description='1 = advisory; 3 = REVISE trigger at threshold; 5 = FORCE-RESOLVE or RE-PLAN.',
            ge=1,
            le=5,
        ),
    ]


class Category(StrEnum):
    PUNCTUATION_TELLS = 'punctuation_tells'
    CONSTRUCTION_TELLS = 'construction_tells'
    HEDGE_TELLS = 'hedge_tells'
    CLICHE_TELLS = 'cliche_tells'
    ABSTRACT_NOUN_STACKING = 'abstract_noun_stacking'
    PREDICTABLE_OPENERS = 'predictable_openers'
    RHYTHM_TELLS = 'rhythm_tells'
    CLOSING_SUMMARY_PATTERNS = 'closing_summary_patterns'
    BESTSELLER_BOT_VOICE = 'bestseller_bot_voice'
    MBSE_CRAFT_REVIEW = 'mbse_craft_review'


class DetectionMethod(StrEnum):
    REGEX = 'regex'
    RULE = 'rule'
    LLM_CRITIC = 'llm_critic'
    STATISTICAL = 'statistical'


class Source(StrEnum):
    ONTOLOGY_V3_S6 = 'ontology_v3_s6'
    MBSE_CRAFT_REVIEW = 'mbse_craft_review'
    CALIBRATION = 'calibration'


class AITellPattern(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pattern_id: Annotated[str, Field(description='Unique slug, e.g. TELL-P-001.')]
    category: Category
    severity: Severity
    description: Annotated[
        str,
        Field(
            description='Plain English explanation of what this tell is and why it reads as AI-generated.'
        ),
    ]
    detection_method: Annotated[
        DetectionMethod, Field(description='How this pattern is detected.')
    ]
    regex_or_rule: Annotated[
        str | None,
        Field(
            description='Regex pattern or deterministic rule expression. Null for LLM-critic-detected patterns.'
        ),
    ] = None
    examples: Annotated[
        list[str] | None,
        Field(
            description='Synthetic (not sourced) example strings that trigger this pattern.'
        ),
    ] = None
    context_required: Annotated[
        bool | None,
        Field(
            description='True if surrounding sentences are needed to evaluate this pattern.'
        ),
    ] = False
    context_window_sentences: Annotated[
        int | None,
        Field(
            description='Sentences of context required when context_required = true.',
            ge=1,
        ),
    ] = None
    suggested_replacement_strategy: Annotated[
        str | None,
        Field(description='How a drafter or editor should address this tell.'),
    ] = None
    density_ceiling_per_1k: Annotated[
        float | None,
        Field(
            description='Maximum acceptable frequency per 1000 words before REVISE is triggered.',
            ge=0.0,
        ),
    ] = None
    source: Annotated[
        Source | None,
        Field(
            description='Provenance: ontology section, MBSE craft review batch, etc.'
        ),
    ] = None


class AITellCatalog(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    catalog_id: str
    version: str
    schema_version: str | None = '1.0.0'
    description: str | None = None
    patterns: Annotated[list[AITellPattern], Field(min_length=1)]
    categories: Annotated[
        list[str] | None,
        Field(
            description='Enumeration of category labels used in patterns.',
            examples=[
                [
                    'punctuation_tells',
                    'construction_tells',
                    'hedge_tells',
                    'cliche_tells',
                    'abstract_noun_stacking',
                    'predictable_openers',
                    'rhythm_tells',
                    'closing_summary_patterns',
                    'bestseller_bot_voice',
                    'mbse_craft_review',
                ]
            ],
        ),
    ] = None
