# generated by datamodel-codegen:
#   filename:  continuity_model.schema.json
#   timestamp: 2026-05-16T15:42:47+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class Character(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    name: str
    aliases: list[str] | None = None
    physical: Annotated[
        dict[str, str] | None,
        Field(
            description='Physical traits (height, build, coloring, distinguishing marks, etc.).'
        ),
    ] = None
    psychological: Annotated[
        dict[str, str] | None,
        Field(description='Core traits, fears, wants, wounds, belief systems.'),
    ] = None
    voice: Annotated[
        dict[str, str] | None,
        Field(
            description='Speech patterns, vocabulary level, tics, idiolect features.'
        ),
    ] = None
    arc: Annotated[
        dict[str, str] | None,
        Field(
            description='Character arc definition: start_state, end_state, transformation_type.'
        ),
    ] = None
    relationships: Annotated[
        list[str] | None,
        Field(description='Relationship IDs involving this character.'),
    ] = None
    backstory: str | None = None
    taboos: Annotated[
        list[str] | None,
        Field(
            description='Things this character would never do/say (continuity hard constraints).'
        ),
    ] = None


class Location(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    name: str
    description: str | None = None
    spatial_relationships: dict[str, str] | None = None
    sensory_anchors: Annotated[
        dict[str, str] | None,
        Field(description='Canonical sensory details by modality.'),
    ] = None


class WorldObject(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    name: str
    description: str | None = None
    properties: dict[str, Any] | None = None
    current_location_id: str | None = None
    current_owner_id: str | None = None


class Concept(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    name: str
    definition: str | None = None
    rules: list[str] | None = None


class Faction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    name: str
    description: str | None = None
    goals: list[str] | None = None
    members: list[str] | None = None


class TimelineEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    event_id: str
    diegetic_time: Annotated[
        str,
        Field(
            description='Canonical timestamp in story time (ISO 8601 or relative era label).'
        ),
    ]
    description: str
    participants: list[str] | None = None
    location_id: str | None = None
    consequences: list[str] | None = None


class Relationship(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    entity_a_id: str
    entity_b_id: str
    relationship_type: Annotated[
        str, Field(description='e.g. rivals, lovers, parent_child, employer_employee.')
    ]
    description: str | None = None
    history: str | None = None


class ContradictionType(StrEnum):
    TYPE_MISMATCH = 'type_mismatch'
    TIMELINE_VIOLATION = 'timeline_violation'
    SPATIAL_VIOLATION = 'spatial_violation'
    CAPABILITY_VIOLATION = 'capability_violation'
    VOICE_VIOLATION = 'voice_violation'
    TABOO_VIOLATION = 'taboo_violation'


class ContinuityModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    book_id: str
    version: str
    schema_version: str | None = '1.0.0'
    characters: Annotated[
        dict[str, Character] | None,
        Field(description='Map of character_id → Character.'),
    ] = None
    locations: dict[str, Location] | None = None
    objects: dict[str, WorldObject] | None = None
    concepts: dict[str, Concept] | None = None
    factions: dict[str, Faction] | None = None
    timeline: Annotated[
        list[TimelineEvent] | None,
        Field(description='Ordered chronological events (diegetic time).'),
    ] = None
    relationships: list[Relationship] | None = None
