# generated by datamodel-codegen:
#   filename:  convergence.schema.json
#   timestamp: 2026-05-16T15:42:47+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class HardFailConditions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bible_contradiction: Annotated[
        Literal[True],
        Field(description='Any unresolved ContinuityModel contradiction → RE-PLAN.'),
    ] = True
    must_have_absent: Annotated[
        Literal[True],
        Field(
            description='A genre/goal required element (trope, beat, promise) is absent → RE-PLAN.'
        ),
    ] = True
    taboo_violation: Annotated[
        Literal[True], Field(description='Any character taboo violated → RE-PLAN.')
    ] = True
    sensitivity_violation_hard: Annotated[
        Literal[True],
        Field(
            description='Sensitivity critic hard veto → RE-PLAN only. Sacred: never FORCE-RESOLVE.'
        ),
    ] = True
    dnf_likelihood_ceiling: Annotated[
        float | None,
        Field(
            description='If DNF likelihood exceeds this value → RE-PLAN. Goal-defined.',
            ge=0.0,
            le=1.0,
        ),
    ] = None


class ReviseConditions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    weighted_critic_score_floor: Annotated[
        float | None,
        Field(
            description='If weighted aggregate critic score < this floor → REVISE.',
            ge=0.0,
            le=10.0,
        ),
    ] = None
    weighted_reader_satisfaction_floor: Annotated[
        float | None,
        Field(
            description='If weighted reader satisfaction < this floor → REVISE.',
            ge=0.0,
            le=1.0,
        ),
    ] = None
    voice_fidelity_distance_ceiling: Annotated[
        float | None,
        Field(description='If voice distance > this ceiling → REVISE.', ge=0.0, le=1.0),
    ] = None
    ai_tell_density_ceiling: Annotated[
        float | None,
        Field(
            description='If AI-tell density (per 1000 words) > this ceiling → REVISE.',
            ge=0.0,
        ),
    ] = None
    specificity_index_floor: Annotated[
        float | None,
        Field(description='If specificity index < this floor → REVISE.', ge=0.0),
    ] = None
    engagement_floor: Annotated[
        float | None,
        Field(description='If engagement score < this floor → REVISE.', ge=0.0, le=1.0),
    ] = None
    promise_ledger_overdue: Annotated[
        Literal[True],
        Field(
            description='Any critical/high promise overdue at chapter boundary → REVISE.'
        ),
    ] = True


class CandidateSelection(StrEnum):
    HIGHEST_WEIGHTED_SCORE = 'highest_weighted_score'
    LOWEST_AI_TELL_DENSITY = 'lowest_ai_tell_density'
    USER_CONFIGURED = 'user_configured'


class ForceResolvePolicy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    candidate_selection: Annotated[
        CandidateSelection,
        Field(description='How to pick the winner among available candidates.'),
    ]
    log_relaxed_thresholds: Annotated[
        Literal[True],
        Field(
            description='Relaxed thresholds must be logged in the decision log and calibration log.'
        ),
    ]
    append_issue_report: Annotated[
        Literal[True],
        Field(description='Issue report entry is required for every FORCE-RESOLVE.'),
    ]
    sacred_thresholds: Annotated[
        list[str] | None,
        Field(
            description='Threshold names that cannot be relaxed even during FORCE-RESOLVE. Sensitivity thresholds are always in this list.'
        ),
    ] = ['sensitivity_violation_hard']


class GoConditions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    never_halts: Annotated[
        Literal[True],
        Field(
            description='Universal invariant: the Convergence Controller never halts waiting for human input.'
        ),
    ] = True


class ConvergenceFunction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    profile_id: Annotated[
        str, Field(description='Genre/Goal profile this convergence config belongs to.')
    ]
    version: str | None = '1.0.0'
    schema_version: str | None = '1.0.0'
    hard_fail_conditions: Annotated[
        HardFailConditions,
        Field(
            description='Any true → RE-PLAN. Sensitivity violations are always RE-PLAN; cannot be FORCE-RESOLVEd.'
        ),
    ]
    revise_conditions: Annotated[
        ReviseConditions,
        Field(description='Any true → REVISE (if max_revise_attempts not exceeded).'),
    ]
    max_revise_attempts: Annotated[
        int | None,
        Field(
            description='Maximum REVISE iterations before escalating to FORCE-RESOLVE.',
            ge=1,
        ),
    ] = 3
    force_resolve_policy: Annotated[
        ForceResolvePolicy,
        Field(
            description='Applied after max_revise_attempts exceeded. Picks highest-scoring candidate, logs relaxed thresholds, appends issue report entry.'
        ),
    ]
    go_conditions: Annotated[
        GoConditions,
        Field(description='All revise conditions pass and no hard fails → GO.'),
    ]
    critic_weights: Annotated[
        dict[str, float] | None,
        Field(
            description='Weight map critic_id → float (sum not required to be 1; normalized at runtime). Genre/Goal profiles extend this.'
        ),
    ] = None
    reader_weights: Annotated[
        dict[str, float] | None,
        Field(description='Weight map reader_persona_id → float.'),
    ] = None
