# generated by datamodel-codegen:
#   filename:  promise_ledger.schema.json
#   timestamp: 2026-05-16T15:42:47+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class PromiseType(StrEnum):
    FORESHADOWING = 'foreshadowing'
    CHEKHOV_OBJECT = 'chekhov_object'
    CHARACTER_QUESTION = 'character_question'
    MYSTERY_THREAD = 'mystery_thread'
    EMOTIONAL_DEBT = 'emotional_debt'
    THEMATIC_SETUP = 'thematic_setup'
    ROMANTIC_TENSION = 'romantic_tension'
    WORLD_QUESTION = 'world_question'


class ResolutionState(StrEnum):
    OPEN = 'open'
    RESOLVED = 'resolved'
    ABANDONED = 'abandoned'
    DEFERRED_TO_SEQUEL = 'deferred_to_sequel'


class Priority(StrEnum):
    CRITICAL = 'critical'
    HIGH = 'high'
    MEDIUM = 'medium'
    LOW = 'low'


class Promise(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    type: PromiseType
    opened_at: Annotated[
        str,
        Field(
            description='Unit ID (chapter/scene/beat) at which this promise was established.'
        ),
    ]
    opened_by: Annotated[
        str, Field(description='Agent ID that created this promise entry.')
    ]
    must_resolve_by: Annotated[
        str,
        Field(
            description='Unit ID by which this promise must be resolved. Overdue = past this unit without resolution.'
        ),
    ]
    resolution_state: ResolutionState
    resolved_at: Annotated[
        str | None,
        Field(description='Unit ID where resolution occurred (null if open).'),
    ] = None
    resolved_by: Annotated[
        str | None, Field(description='Agent ID that committed the resolution.')
    ] = None
    priority: Priority
    description: Annotated[
        str, Field(description='Plain-language description of the promise.')
    ]
    acceptable_resolutions: Annotated[
        list[str] | None,
        Field(
            description='Enumerated resolution strategies the Convergence Controller may accept.'
        ),
    ] = None
    convergence_note: Annotated[
        str | None,
        Field(
            description='FORCE-RESOLVE note if resolution was forced (logged for issue report).'
        ),
    ] = None


class PromiseLedger(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    book_id: str
    version: str | None = '1.0.0'
    schema_version: str | None = '1.0.0'
    promises: Annotated[
        list[Promise],
        Field(description='Append-only; do not delete or modify existing entries.'),
    ]
