# generated by datamodel-codegen:
#   filename:  specificity_heuristics.schema.json
#   timestamp: 2026-05-16T15:42:47+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class ConcreteNounCountPerScene(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    floor: Annotated[int, Field(ge=0)]
    target: Annotated[int | None, Field(ge=0)] = None
    ceiling: Annotated[int | None, Field(ge=0)] = None


class ProperNounDensity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    floor: Annotated[float, Field(ge=0.0)]
    target: float | None = None
    ceiling: float | None = None


class CulturalSpecificityIndex(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    floor: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    target: Annotated[float | None, Field(ge=0.0, le=1.0)] = None


class TemporalAnchoring(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    required_per_n_scenes: Annotated[
        int | None,
        Field(
            description='A time anchor (day, hour, season, era marker) must appear at least once per this many scenes.',
            ge=1,
        ),
    ] = None


class SpatialAnchoring(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    must_establish_within_words: Annotated[
        int | None,
        Field(
            description='A location anchor must appear within the first N words of a scene.',
            ge=1,
        ),
    ] = None


class FrequencyBand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    floor: Annotated[float | None, Field(ge=0.0)] = None
    target: Annotated[float | None, Field(ge=0.0)] = None
    ceiling: Annotated[float | None, Field(ge=0.0)] = None


class SensoryAnchorFrequency(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    visual: FrequencyBand | None = None
    auditory: FrequencyBand | None = None
    olfactory: FrequencyBand | None = None
    gustatory: FrequencyBand | None = None
    tactile: FrequencyBand | None = None
    proprioceptive: FrequencyBand | None = None
    any_modality_floor: Annotated[
        float | None,
        Field(
            description='Minimum total sensory anchors across all modalities per 1000 words.',
            ge=0.0,
        ),
    ] = None


class SpecificityHeuristics(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    profile_id: Annotated[
        str, Field(description='Genre/Author profile ID this heuristic set belongs to.')
    ]
    version: str | None = '1.0.0'
    schema_version: str | None = '1.0.0'
    concrete_noun_count_per_scene: Annotated[
        ConcreteNounCountPerScene | None,
        Field(description='Target range for number of concrete nouns per scene.'),
    ] = None
    proper_noun_density: Annotated[
        ProperNounDensity | None,
        Field(
            description='Proper nouns per 1000 words — names, places, brands anchor the reader in a specific world.'
        ),
    ] = None
    sensory_anchor_frequency: Annotated[
        SensoryAnchorFrequency | None,
        Field(description='Sensory anchors per 1000 words by modality.'),
    ] = None
    cultural_specificity_index: Annotated[
        CulturalSpecificityIndex | None,
        Field(
            description='Fraction of culturally-specific nouns (brand names, institutions, regional slang, era markers) among all nouns.'
        ),
    ] = None
    temporal_anchoring: Annotated[
        TemporalAnchoring | None,
        Field(description='At least one explicit temporal anchor per N scenes.'),
    ] = None
    spatial_anchoring: Annotated[
        SpatialAnchoring | None,
        Field(description='Scene-opening spatial grounding requirement.'),
    ] = None
