# generated by datamodel-codegen:
#   filename:  structural_hierarchy.schema.json
#   timestamp: 2026-05-16T15:42:47+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class UnitType(StrEnum):
    BOOK = 'book'
    PART = 'part'
    ACT = 'act'
    CHAPTER = 'chapter'
    SCENE = 'scene'
    BEAT = 'beat'


class UnitState(StrEnum):
    UNSPECCED = 'unspecced'
    SPECCED = 'specced'
    DIRTY_DRAFT = 'dirty_draft'
    NEEDS_REVIEW = 'needs_review'
    APPROVED = 'approved'
    FINAL = 'final'


class BeatData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    function: Annotated[
        str | None,
        Field(
            description='Beat function label (e.g. establish_tension, reveal, deflect, payoff).'
        ),
    ] = None
    intensity: Annotated[
        float | None,
        Field(description='Genre-defined intensity scale value.', ge=0.0, le=10.0),
    ] = None
    pov_character_id: str | None = None
    location_id: str | None = None
    time_marker: str | None = None
    characters_present: list[str] | None = None
    expected_reader_response: str | None = None
    setup_for: Annotated[
        list[str] | None, Field(description='Unit IDs this beat sets up.')
    ] = None
    payoff_of: Annotated[
        list[str] | None, Field(description='Unit IDs this beat pays off.')
    ] = None
    cause_of: Annotated[
        list[str] | None, Field(description='Unit IDs this beat causally enables.')
    ] = None
    caused_by: Annotated[
        list[str] | None,
        Field(description='Unit IDs that causally necessitate this beat.'),
    ] = None


class SceneData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    goal: Annotated[
        str | None,
        Field(description='Scene goal (MRU: Motivation-Reaction Unit goal).'),
    ] = None
    conflict: Annotated[
        str | None, Field(description='Obstacle or opposition encountered.')
    ] = None
    outcome: Annotated[
        str | None, Field(description='Scene outcome: disaster, trade-off, or success.')
    ] = None
    state_delta: Annotated[
        dict[str, str] | None,
        Field(description='Changes to world/character state this scene commits.'),
    ] = None
    beats: Annotated[
        list[str] | None, Field(description='Ordered beat IDs (children of type beat).')
    ] = None


class ChapterData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    hook: Annotated[str | None, Field(description='Opening hook summary.')] = None
    cliffhanger_required: bool | None = False
    pov_character_id: str | None = None
    scenes: Annotated[list[str] | None, Field(description='Ordered scene IDs.')] = None


class ActPartData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    arc_function: Annotated[
        str | None,
        Field(description='e.g. setup, confrontation, resolution; genre-defined.'),
    ] = None
    chapters: Annotated[list[str] | None, Field(description='Ordered chapter IDs.')] = (
        None
    )


class GenericUnit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    parent_unit_id: str | None = None
    position: Annotated[int, Field(description='1-based ordinal among siblings.', ge=1)]
    unit_type: UnitType
    target_word_count: Annotated[int | None, Field(ge=1)] = None
    actual_word_count: Annotated[int | None, Field(ge=0)] = None
    function: Annotated[
        str | None, Field(description='Narrative function this unit serves.')
    ] = None
    entry_state: Annotated[
        str | None, Field(description='Diegetic world state at start of this unit.')
    ] = None
    exit_state: Annotated[
        str | None, Field(description='Diegetic world state at end of this unit.')
    ] = None
    state: UnitState
    children: Annotated[
        list[GenericUnit] | None,
        Field(description='Ordered child units. Discriminated by unit_type.'),
    ] = None
    beat_data: BeatData | None = None
    scene_data: SceneData | None = None
    chapter_data: ChapterData | None = None
    act_part_data: ActPartData | None = None


class StructuralHierarchy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    book_id: str
    version: str | None = '1.0.0'
    root_unit: GenericUnit


GenericUnit.model_rebuild()
