# generated by datamodel-codegen:
#   filename:  voice_axes.schema.json
#   timestamp: 2026-05-16T15:42:47+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class SentenceLengthDistribution(BaseModel):
    very_short: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    short: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    medium: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    long: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    very_long: Annotated[float | None, Field(ge=0.0, le=1.0)] = None


class SentenceOpenerDistribution(BaseModel):
    subject: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    adverbial: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    participial: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    coordinating_conjunction: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    prepositional: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    other: Annotated[float | None, Field(ge=0.0, le=1.0)] = None


class SentenceMoodDistribution(BaseModel):
    declarative: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    interrogative: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    imperative: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    exclamatory: Annotated[float | None, Field(ge=0.0, le=1.0)] = None


class SentenceLevel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sentence_length_mean: Annotated[
        float, Field(description='Mean words per sentence.', ge=1.0)
    ]
    sentence_length_std: Annotated[
        float, Field(description='Standard deviation of words per sentence.', ge=0.0)
    ]
    sentence_length_distribution: Annotated[
        SentenceLengthDistribution | None,
        Field(
            description='Fraction of sentences in length buckets (1–5, 6–12, 13–20, 21–35, 36+).'
        ),
    ] = None
    sentence_opener_distribution: Annotated[
        SentenceOpenerDistribution | None,
        Field(
            description='Fraction of sentences starting with each syntactic category.'
        ),
    ] = None
    sentence_opener_entropy_min: Annotated[
        float | None,
        Field(
            description='Minimum Shannon entropy of opener distribution (diversity floor).',
            ge=0.0,
        ),
    ] = None
    sentence_mood_distribution: Annotated[
        SentenceMoodDistribution | None,
        Field(description='Fraction of sentences in each mood.'),
    ] = None


class Metric(StrEnum):
    TTR = 'TTR'
    MTLD = 'MTLD'
    VOCD_D = 'vocd_D'


class LexicalDiversityTarget(BaseModel):
    metric: Metric
    min: float
    target: float
    max: float


class FormalityRegister(StrEnum):
    VERY_CASUAL = 'very_casual'
    CASUAL = 'casual'
    NEUTRAL = 'neutral'
    FORMAL = 'formal'
    VERY_FORMAL = 'very_formal'


class SensoryTokenDensity(BaseModel):
    visual: Annotated[float | None, Field(ge=0.0)] = None
    auditory: Annotated[float | None, Field(ge=0.0)] = None
    olfactory: Annotated[float | None, Field(ge=0.0)] = None
    gustatory: Annotated[float | None, Field(ge=0.0)] = None
    tactile: Annotated[float | None, Field(ge=0.0)] = None
    proprioceptive: Annotated[float | None, Field(ge=0.0)] = None


class Lexical(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    lexical_diversity_target: Annotated[
        LexicalDiversityTarget, Field(description='TTR/MTLD target range.')
    ]
    formality_register: FormalityRegister
    rare_word_frequency: Annotated[
        float | None,
        Field(
            description='Fraction of tokens with frequency rank > 10000 in reference corpus.',
            ge=0.0,
            le=1.0,
        ),
    ] = None
    concrete_noun_ratio: Annotated[
        float | None,
        Field(description='Ratio of concrete to total nouns.', ge=0.0, le=1.0),
    ] = None
    sensory_token_density: Annotated[
        SensoryTokenDensity | None,
        Field(description='Sensory tokens per 1000 words by modality.'),
    ] = None


class StructuralProse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dialogue_to_narration_ratio: Annotated[
        float | None,
        Field(
            description='Words in dialogue tags+speech / total words. Range 0–1.',
            ge=0.0,
        ),
    ] = None
    internal_monologue_share: Annotated[
        float | None,
        Field(
            description='Fraction of narration that is free indirect discourse or tagged thought.',
            ge=0.0,
            le=1.0,
        ),
    ] = None
    figurative_language_frequency: Annotated[
        float | None, Field(description='Metaphors + similes per 1000 words.', ge=0.0)
    ] = None


class PunctuationSignature(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    em_dash_rate_max: Annotated[
        float | None, Field(description='Maximum em dashes per 1000 words.', ge=0.0)
    ] = None
    semicolon_rate: Annotated[
        float | None, Field(description='Semicolons per 1000 words.', ge=0.0)
    ] = None
    ellipsis_rate: Annotated[
        float | None, Field(description='Ellipses per 1000 words.', ge=0.0)
    ] = None
    parenthetical_rate: Annotated[
        float | None,
        Field(description='Parenthetical phrase pairs per 1000 words.', ge=0.0),
    ] = None
    comma_density: Annotated[
        float | None, Field(description='Commas per 1000 words.', ge=0.0)
    ] = None


class ParagraphLengthDistribution(BaseModel):
    single_sentence: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    short: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    medium: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    long: Annotated[float | None, Field(ge=0.0, le=1.0)] = None


class Cadence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    short_long_alternation_index: Annotated[
        float | None,
        Field(
            description='0 = monotone lengths, 1 = maximal alternation.', ge=0.0, le=1.0
        ),
    ] = None
    paragraph_length_mean: Annotated[
        float | None, Field(description='Mean words per paragraph.', ge=1.0)
    ] = None
    paragraph_length_distribution: ParagraphLengthDistribution | None = None


class ModalityAndStance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    modal_hedge_frequency: Annotated[
        float | None,
        Field(
            description='Modal verbs (could, might, would, etc.) per 1000 words.',
            ge=0.0,
        ),
    ] = None
    adverb_density: Annotated[
        float | None, Field(description='Adverbs per 1000 words.', ge=0.0)
    ] = None
    adjective_stacking_max: Annotated[
        int | None,
        Field(
            description='Maximum consecutive pre-nominal adjectives before flagging.',
            ge=1,
        ),
    ] = None


class PovDistanceDefault(StrEnum):
    DEEP = 'deep'
    MODERATE = 'moderate'
    SHALLOW = 'shallow'
    OMNISCIENT = 'omniscient'


class TimeOfNarration(StrEnum):
    IMMEDIATE = 'immediate'
    RETROSPECTIVE = 'retrospective'
    MIXED = 'mixed'


class PovCraft(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pov_distance_default: Annotated[
        PovDistanceDefault | None,
        Field(description="Default psychic distance for this author's POV."),
    ] = None
    narrator_intrusion_frequency: Annotated[
        float | None,
        Field(
            description='Authorial narrator intrusions per chapter (0 = pure close third/first).',
            ge=0.0,
        ),
    ] = None
    time_of_narration: TimeOfNarration | None = None


class WhitelistedConstruction(BaseModel):
    pattern: str
    min_frequency_per_10k: float


class Validation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    voice_distance_threshold: Annotated[
        float,
        Field(
            description='Maximum aggregate voice distance (normalized) before REVISE.',
            ge=0.0,
            le=1.0,
        ),
    ]
    blacklisted_constructions: Annotated[
        list[str] | None,
        Field(
            description='Regex patterns for constructions never used by this author.'
        ),
    ] = None
    whitelisted_constructions: list[WhitelistedConstruction] | None = None
    tolerance_band_sigma: Annotated[
        float | None,
        Field(
            description='Axis value must be within ±N sigma of profile target to pass.'
        ),
    ] = 1.5


class VoiceAxes(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    profile_id: Annotated[
        str, Field(description='Author profile this voice spec belongs to.')
    ]
    version: str | None = '1.0.0'
    sentence_level: SentenceLevel
    lexical: Lexical
    structural_prose: StructuralProse
    punctuation_signature: PunctuationSignature
    cadence: Cadence
    modality_and_stance: ModalityAndStance
    pov_craft: PovCraft
    validation: Annotated[
        Validation, Field(description='Convergence criteria for voice fidelity.')
    ]
